services:
  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_DATABASE: prog_test
      MYSQL_USER: naruto
      MYSQL_PASSWORD: PNSJkxXvVNDAhePMuExTBuRR
      MYSQL_ROOT_PASSWORD: PNSJkxXvVNDAhePMuExTBuRR
      TZ: Asia/Jakarta
    volumes:
      - ./docker/prog_test-db/conf.d":/etc/mysql/conf.d
      - ./storage/docker/prog_testdb-data":/var/lib/mysql
    ports:
      - 6603:3306
    expose:
      - 6603